services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "8001:8000"  # Change this line to map container's port 8000 to host's 8001

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
